### ISSUE TITLE
Change Entry Creator gone

### ISSUE THREAD

**Issue by slydawgg** [katzwebservices/GravityView#324]
I've tried to go in and notice that there is a missing field from previous versions.
If you will notice in a video I did a few months back (http://youtu.be/wHhMVJOc4mI starting at 2:10) you will see the Admin could edit who was the Entry Creator and who had ability to make changes, but no longer has that ability.
Any ideas?

![screen shot 2015-02-10 at 11 39 07 am](https://cloud.githubusercontent.com/assets/8378724/6131388/683bf628-b119-11e4-9b34-1d6a79a3b934.png)

**Comment by zackkatz** [comment]
![screen shot 2015-02-18 at 5 21 23 pm](https://cloud.githubusercontent.com/assets/870979/6259680/96489a1a-b792-11e4-8911-dfa090b254e1.png)

Can you send a login to support@gravityview.co ?

**Comment by zackkatz** [comment]
@slydawgg Are you still not seeing the Change Entry Creator?

**Comment by zackkatz** [comment]
@slydawgg Let us know if you're still having this issue.
