### ISSUE TITLE
Array to string conversion E_NOTICE

### ISSUE THREAD

**Issue by signo** [katzwebservices/GravityView#332]
In the file includes\class-frontend-views.php i am geting the following error notice when debug is set to on.

E_NOTICE: Array to string conversion 
The error is located on line 151, where the implode function is used
 
```php
// No $_GET parameters
if( empty( $_GET ) || !is_array( $_GET ) ) {
    return false;
}
// Get the value of $_GET
$search_values = implode( '', array_values( $_GET ) );
// If the $_GET parameters are set, but they're empty, it's no search.
`

**Comment by signo** [comment]
The problem is that implode will trigger this error when an array items is also an array, for now i am fixing it by replacing the following code, of course this will fail if one of the sub items is an array, but ir works for me fo the time being.

```php
		$search_values = '';
		foreach ( $_GET as $key => $value) {
			$search_values .= is_array( $value ) ? implode( '', array_values( $value ) ) : $value;
		}
`

**Comment by zackkatz** [comment]
@signo Thanks for reporting. Can you provide a sample URL that triggered this error?

**Comment by signo** [comment]
This error occurs on every frontend url that has parameters, in my case it happens when i use the following url http://example.com?cliente=username

**Comment by zackkatz** [comment]
@signo I'm closing this issue; if you encounter the problem again, let us know. Thanks!
