### ISSUE TITLE
Extending Make Visible For list and missing action for custom validation to match

### ISSUE THREAD

**Issue by Idealien** [katzwebservices/GravityView#346]
The gravityview_field_visibility_caps lets me extend the list of options a field can conditionally displayed. Even extending around gravityview_template_edit_link_options can let me turn the edit link on for a new scenario (role or user meta data).

But both rely on GravityView_Edit_Entry::check_user_cap_edit_entry which looks to whether:
* Admin can access all
* User created the entry

There isn't an action which would correspond to what I attach to gravityview_field_visibility_caps to perform custom validation.

**Comment by zackkatz** [comment]
@Idealien Thanks for the feedback. This is being tested for inclusion in the next update!
