### ISSUE TITLE
IE8 - WP Dev Mode - fe-views.js causes JS error

### ISSUE THREAD

**Issue by Idealien** [katzwebservices/GravityView#361]
Error:
Expected identifier, string or number
fe-views.js Line: 165 / Char 2

Version 1.7.6.2

Having WP_DEBUG = false via wp-config resolves the issue (loads .min.js file)
As does removing the extra , at end of backGetCookie function definition.

Stupid IE8 - why won't you just go away. Nobody likes you. If we were in high school and picking teams for dodgeball, most people would chose to play a teammate down than have you.

**Comment by bordoni** [comment]
Thanks for the report @Idealien!
As soon as we have a good hold of some bigger issues (new version) we will tackle this one.

**Comment by zackkatz** [comment]
@Idealien We'll be releasing an update with this fix later today. Thanks for the fix!
