### ISSUE TITLE
Wrong template file being called for an extension

### ISSUE THREAD

**Issue by rafaehlers** [katzwebservices/GravityView#443]
This KB says one thing: http://docs.gravityview.co/article/64-how-to-override-gravityview-templates

However, that doesn't apply to templates from extensions, on this particular case, Ratings & Reviews. 

The user wanted to change some text that was inside the file: 
> wp-content/plugins/gravityview-ratings-reviews/includes/templates/review-list-header.php

But when copying this file to the gravityview folder inside his current's theme, it didn't worked:
> wp-content/themes/twentyfifteen/gravityview/review-list-header.php

In order to make it work, we had to remove the review- part from the file name, like this:
> wp-content/themes/twentyfifteen/gravityview/list-header.php

That worked!

So, in this case, either the Docs are wrong, or the way to grab the template files are wrong.

**Comment by zackkatz** [comment]
This is an issue with the Ratings & Reviews extension. See katzwebservices/GravityView-Ratings-Reviews/#76
