### ISSUE TITLE
Changing username display after edit

### ISSUE THREAD

**Issue by charliebartlett** [katzwebservices/GravityView#450]
I have a sample form I filled in an saved logged in as a test user. After editing this form through GV as the test user, it changes the users settings "Display name publicly as" from "First Last" to "username". 

It initially displays the correct username, until an entry is edited with GV.

WP 4.2.3 / GF 1.9.12.1

**Comment by zackkatz** [comment]
Thanks for letting us know!

**Comment by zackkatz** [comment]
@charliebartlett Do you have User Registration Addon enabled?

**Comment by charliebartlett** [comment]
Yes it is enabled.

**Comment by zackkatz** [comment]
This is fixed in 1.14 (coming soon). Thanks for reporting!
