### ISSUE TITLE
html as Link Text

### ISSUE THREAD

**Issue by m-e-h** [katzwebservices/GravityView#495]
Both **Edit Entry** and **Delete Entry** fields accept html `<i class="material-icons">add</i>` for the **Link Text** but **Source URL** does not. Not sure if this is expected behavior. Just assuming they should work the same..?

**Comment by zackkatz** [comment]
This is in 1.14, coming soon. Thanks!

**Comment by m-e-h** [comment]
Dude, you're on it! Thanks!
