### ISSUE TITLE
data-icon selector in admin-global.css

### ISSUE THREAD

**Issue by m-e-h** [katzwebservices/GravityView#503]
Is it possible to use a more specific selector for GV icons?
https://github.com/katzwebservices/GravityView/blob/master/assets/css/scss/font.scss#L19-L21

This is from this plugin https://wordpress.org/plugins/wp-term-icons/
![dataicon](https://cloud.githubusercontent.com/assets/3585901/9689612/3ec186b2-5305-11e5-86d1-1945781b46da.png)

Minus the styles linked above it looks like this
![dataicon2](https://cloud.githubusercontent.com/assets/3585901/9689646/7ccbb0ae-5305-11e5-8792-6532cc3ae855.png)

**Comment by zackkatz** [comment]
Yeah, totally—we'll fix this soon. Thanks for pointing it out!
