### ISSUE TITLE
A-Z Filters stopped working

### ISSUE THREAD

**Issue by zackkatz** [katzwebservices/GravityView#525]
Multiple users report A-Z filters stopped working for them after ~1.13.1

**Comment by zackkatz** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bUTiNZZo&#x2F;1-a-z-filters-not-working"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> A-Z Filters not working</a>

**Comment by luistinygod** [comment]
I think this is related with the following https://github.com/katzwebservices/GravityView-AZ-Filters/commit/6044d5fcdf1eadfd7f8a7a8ee63d70630759c82b.
I noticed the version 1.0.5 was not alerting for new version 1.0.6.

**Comment by luistinygod** [comment]
Waiting for customer feedback. (HS 3406 & HS 3360)

**Comment by luistinygod** [comment]
Customer HS 3406 confirmed version 1.0.6 fixes the issue.
This is caused by a conflict with Gravity Forms version 1.9.12+
