### ISSUE TITLE
User Registration error

### ISSUE THREAD

**Issue by m-e-h** [katzwebservices/GravityView#526]
When a new registration via the GF User Registration plugin, I get this
```
Warning: Invalid argument supplied for foreach() in /nas/wp/www/staging/gitrcdoc/wp-content/plugins/gravityview/includes/extensions/edit-entry/class-edit-entry-user-registration.php on line 125
```
I do not have a View connected to that form either. I haven't done much troubleshooting with it and I may have done something wrong, but it looks like you made a couple recent commits around that area sooo...

**Comment by zackkatz** [comment]
Hey @m-e-h - We've got this fixed in the next update. Thanks for reporting!

**Comment by zackkatz** [comment]
Done in 1.15. Thanks again for reporting.
