### ISSUE TITLE
User Registration Addon resets password for users

### ISSUE THREAD

**Issue by zackkatz** [katzwebservices/GravityView#532]
- `GFUser::update_user( $entry, $form, $config );`  is being called regardless of feed configuration. It should only be trigged on `update` feeds, not `create` feeds.
- Roles don't need to be overridden. The Gravity Forms User Registration settings already have an option for preserving existing roles

**Comment by zackkatz** [comment]
See https://secure.helpscout.net/conversation/note/126139566/3534/

**Comment by rafaehlers** [comment]
Working fine on my tests
