### ISSUE TITLE
sanitize_html_class

### ISSUE THREAD

**Issue by m-e-h** [katzwebservices/GravityView#555]
Any way you may consider moving away from this to an alternative like `esc_attr()`
It's killing my media query classes which use @ before the suffix, like `3-col@md`.

I submitted a ticket to core but I don't think anything will come of it. https://core.trac.wordpress.org/ticket/33924

**Comment by zackkatz** [comment]
@m-e-h - You'll be able to define your own `gravityview_sanitize_html_class()` function in the next update!

**Comment by m-e-h** [comment]
Thats awesome. Thanks so much!
