### ISSUE TITLE
Hide Empty Fields option prevents Sections fields from showing

### ISSUE THREAD

**Issue by rafaehlers** [katzwebservices/GravityView#557]
GF Section fields won't display if the option "Hide Empty Fields" is checked:

![hide-empty-fields](https://cloud.githubusercontent.com/assets/1222472/10627156/e42c2900-7794-11e5-87b5-8c693c1c439f.jpg)

**Comment by zackkatz** [comment]
Fixed with https://github.com/katzwebservices/GravityView/commit/c1d647d20339c2288ec2f0c8402bbc782287ad84
