### ISSUE TITLE
Disable ?post_type=gravityview access

### ISSUE THREAD

**Issue by zackkatz** [katzwebservices/GravityView#564]
It's possible to display all Views by adding `?post_type=gravityview` to the site URL. This should be disabled by default.

**Comment by Idealien** [comment]
Very closely related to this - an option to configure whether views should be accessible (or not) outside of shortcode / page display. A method to identify - per view - whether the /view/slug-of-entry should be accessible to all or not.

**Comment by zackkatz** [comment]
Yes, @Idealien - I've been planning this as well. Thanks!
